### ISSUE TITLE
batchFrequency is hard code to zero?

### ISSUE THREAD

**Issue by xujihui1985** [kdar/logrus-cloudwatchlogs#10]
just wonder why batchFrequency is hard code to zero? and Write method of Hook struct looks wired

```
	if lastErr, ok := <-h.err; ok {
			return 0, fmt.Errorf("%v", lastErr)
	}
```
if there is no err written to err chan, it will just hang and not return?

**Comment by kdar** [comment]
Hey! Sorry for the late reply. I haven't used this package since my old job from over a year ago. If you would like to submit a PR I would happily merge it.

**Comment by xujihui1985** [comment]
thanks for the reply, I was writing my own hook at that time, and I found your repo and read your code, it's really helpful. A big thanks to you. Just a little confuse at that line of code.
