### ISSUE TITLE
Sirupsen case change

### ISSUE THREAD

**Issue by freman** [kdar/logrus-cloudwatchlogs#6]
Sirupsen is now sirupsen

**Comment by kdar** [comment]
Seems to link to the same thing. Still go gettable.

**Comment by freman** [comment]
Falls over if you have other code in your project that uses the lower case import

**Comment by thessem** [comment]
Yep, this makes it impossible to use this package with any other package that uses the lower case variant (which is the standard)

**Comment by kdar** [comment]
Don't be afraid to send a pull request in the future! :)
